name = "orchestera-hub"
main = "src/server.ts"
compatibility_date = "2026-02-20"

[[d1_databases]]
binding = "DB"
database_name = "orchestera-hub-db"
database_id = "045e591a-a75a-49c7-9e2c-5e4dd4333295"

[[queues.producers]]
queue = "jobs-queue"
binding = "JOBS_QUEUE"
