name = "orchestera-hub"
main = "dist/server.js"
compatibility_date = "2026-02-20"

[[d1_databases]]
binding = "DB"
database_name = "orchestera-hub-db"
database_id = "placeholder"

[[queues.producers]]
queue = "jobs-queue"
binding = "JOBS_QUEUE"
